### ISSUE TITLE
online inference

### ISSUE THREAD

**Issue by Zumbalamambo** [StevenLiuWen/ano_pred_cvpr2018#2]
How do I make online inference?

**Comment by StevenLiuWen** [comment]
@Zumbalamambo 
One rough way to online inference could be setting a threshold of PSNR, name \epsilon. On video streaming, when a new frame (t) is coming, calculating the PSNR (t) between the predicted frame and  ground truth frame. If the PSNR (t) < \epsilon, then this frame will be classified as anomalies, otherwise it is normal.  The slight problem is that the threshold (\epsilon) need to tune on validation data set, while there are no validation set on most of the public datsets, such as UCSD Ped1 & 2, CUHK Avenue and ShanghaiTech.
