### ISSUE TITLE
From your experience, what should the training history look like, and what are some good training strategies for your network?

### ISSUE THREAD

**Issue by Santana18** [StevenLiuWen/ano_pred_cvpr2018#5]
Tested it on some new data out of interest. Is this a behavior that you saw during your training https://imgur.com/a/fiSc0iQ ? Did you implement any loss balancing strategies for the generator and the discriminator, e.g. only train one, if it isn't too much stronger than its adversary etc.?

**Comment by StevenLiuWen** [comment]
In my experience, when the adv_loss comes to 0.5 (as the same time, dis_loss comes to 0), then i will stop training, since when the prediction network arrives at this circumstance, the network will be somewhat broken and the PSNR will be low. Next, i will decrease the learning rate of generator and discriminator by 0.1 times and then continue training.
